name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: git submodule update --init
      name: Checkout submodules
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm i -g typescript
    - run: npm ci
    - run: tsc
    - run: node deploy.js
    - uses: actions/upload-artifact@v2
      with:
        name: Reelism
        path: out/reelism.jar